### ISSUE TITLE
Support for different types of button flashing

### ISSUE THREAD

**Issue by KupoMarianne** [mate-desktop-legacy-archive/libmatewnck#1]
I've filed a feature request in mate-applets about the panel window list, as with my disabilities (neurological stuff that interferes with memory and sensory processing, though I believe my requests could be of use to people with various visual impairments, and maybe unimpaired users too), about the way the window buttons flash/pulsate when a window's trying to get attention - currently they flash/pulsate about 5 times then settle in a dim coloured state (which is hard for me to notice), my request was an option to allow the buttons to flash indefinitely, and possibly at a user set speed. Anyway, I've been told by people in the MATE IRC channel that I should file it here too, as apparently libmatewnck is responsible for making the buttons flash, so presumably you'd need to make some minor modifications for this feature to be possible? Thanks lots, it'd really help out a disabled user who really loves her MATE setup :)

**Comment by raveit65** [comment]
marked as can be closed.
libmatewnck is obsolete and i'm in doubt that someone will work on this ;)
