### ISSUE TITLE
shortcut for window selector & window filter

### ISSUE THREAD

**Issue by bftanase** [mate-desktop-legacy-archive/libmatewnck#2]
The window selector applet is such a great little widget! Do you know what it would make it really awesome?

An Eclipse IDE like behaviour (think Ctrl+E shortcut - Quick Switch Editor):
- When pressing a key combination the window list should display;
- This also should display a filter search box to quickly locate needed window
- for bonus points the order should be the most recently used on top.

Use case example:
press [Winkey+E], type some letters to locate some window, [Enter] - no need to touch the mouse

See the eclipse screenshot for an example.

![eclipse-quick-switch](https://f.cloud.github.com/assets/1143666/324045/1bf04516-9ad8-11e2-8764-ed23d3a5b986.png)

**Comment by stefano-k** [comment]
Closing, because we migrated to libwnck
