### ISSUE TITLE
libmatewnck update broke mate-applets

### ISSUE THREAD

**Issue by maradam** [mate-desktop-legacy-archive/libmatewnck#5]
In Mint 13 Maya wit backported mate 1.6
the recent mint ubdate introduced new version of libmatewnck.
libmatewnck-common
libmatewnck-bin
libmatewnck0
changed the version: 1.6.0-1 -> 1.6.1-1

Unfortunately libmatewnck package itself is still held in version 1.6.0-1.
As it depends on libmatewnck-common (than is in 1.6.1-1 version) it became uninstallable and was removed automatically.

The other dependent packages, e.g. mate-applets this way became uninstallable and were removed.

So we have no frequency monitor, system monitor, weather applet and all these other useful things we love mate for.

**Comment by stefano-k** [comment]
This is a distribution issue, not upstream
